pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet build -c Release
  displayName: 'dotnet build'
- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish'
- task: PublishBuildArtifacts@1
  